#!/usr/bin/env python2.7
import sys
from marff import read_arff
import numpy as np
arff = sys.argv[1]
npy = sys.argv[2]

_, arff_data = read_arff(arff)
np_data, np_targets = np.load(npy)

assert len(arff_data) == len(np_data)
i = 0
for arff_inst, np_data_inst, np_target_inst in zip(arff_data, np_data, np_targets):
    assert len(arff_inst) == len(np_data_inst) + 1
    assert arff_inst == list(np_data_inst) + [np_target_inst]
    i += 1
