#!/usr/bin/env python
import sys
# arg1 : data folder
# arg2 : data name (ex : benchmark_VectSum.arff)
# arg3 : cv results dir
multiboost_cmd = "./multiboost --traintest %(folder)s/%(data)s_train_%(ind)d %(folder)s/%(data)s_test_%(ind)d 2000 --fileformat arff  --baselearnertype TreeLearner 20 --outputinfo %(cv_results_dir)s/results%(ind)d --shypname %(cv_results_dir)s/model%(ind)d"

data = sys.argv[2]
nb_batches = 10
import os
for ind in xrange(nb_batches):
    cmd = multiboost_cmd % {"ind": ind, "data": data, "folder": sys.argv[1], "cv_results_dir" : sys.argv[3]}
    print cmd
    a = os.system(cmd)
    print a
