#!/usr/bin/env python
import sys
# arg1 : arff file
# arg2 : nb batches
file = sys.argv[1]
from marff import read_arff, write_arff
import os.path
header, data = read_arff(file)
import random

nb_batches = int(sys.argv[2])
cv_dir = "cv"

per_batch = len(data) / nb_batches
ind = 0

_, file = os.path.split(file)
for first in xrange(0, len(data), per_batch):
    last = min(first + per_batch, len(data))
    if ind == nb_batches - 1:
        last = len(data)

    train = data[0:first] + data[last:]
    test = data[first:last]
    write_arff(header, train, '%s/%s_train_%d' % (cv_dir, file, ind))
    write_arff(header, test, '%s/%s_test_%d' % (cv_dir, file, ind))

    if ind == nb_batches - 1:
        break
    ind += 1

