#!/usr/bin/env python
import sys
from marff import read_arff
import numpy as np
from ndhash import ndhash

D = []
for f in sys.argv[1:]:
    header, data = read_arff(f)
    D.append(data)

for L in zip(*D):
    print " ".join(map(lambda l:str(ndhash(np.array(l[0:-1]))), L))
