#!/usr/bin/env python
import sys
# arg 1 : list of  source
# arg 2 : mapping of source -> dest
mapping = {}
for L in open(sys.argv[2], "r").readlines():
    src, dst = L[0:-1].split()
    mapping[src] = dst

for L in open(sys.argv[1], "r").readlines():
    print mapping[L[0:-1]]
