#!/usr/bin/env python

import sys
# arg 1 : first arff file
# arg 2 : second arff file
# arg 3:  output arff
from marff import read_arff, write_arff

header, data = read_arff(sys.argv[1])
_, data2 = read_arff(sys.argv[2])

write_arff(header, data + data2, sys.argv[3])
