#!/usr/bin/env python

import numpy as np
import sys
from marff import export2arff
# arg 1 : numpy file
# arg2 : arff out file
inputs, targets = np.load(sys.argv[1])
inputs = np.array(list(inputs))
targets_names = tuple(set(targets))
filename = sys.argv[2]
relationName = "noname_relation"
output_folder = "."

export2arff(inputs, targets, targets_names, filename, relationName, output_folder)
