#!/usr/bin/env python2.7
import sys
import numpy as np
import json
import struct
import ctypes

# arg 1 : npy file
# arg2 : b output file
data, target = np.load(sys.argv[1])
f = open(sys.argv[2], "w")

data_ = []
nb = len(data)
f.write(struct.pack('<i', nb))

for i, e in enumerate(data):
    T = 1 if target[i]=='elastic' else 0
    E =  e+ [T]
    array = (ctypes.c_float * len(E))()
    for m in xrange(len(E)):
        array[m] = E[m]
    f.write(bytearray(array)) 
f.close()
