#!/usr/bin/env python
import sys
import numpy as np

operations = sys.argv[1:]

numbers = []
for n in sys.stdin:
    try:
        n = float(n)
        numbers.append(n)
    except:
        continue

res = []
for operation in operations:
    f = getattr(np, operation)
    res.append(f(numbers))
print " ".join(map(str,res))
