#!/usr/bin/env python
import sys
from marff import read_arff, write_arff
#arg1 : filename arff
#arg2 : nb elements
#arg3 : out filename arff 
arff = sys.argv[1]
nb_elements = int(sys.argv[2])
outarff = sys.argv[3]

header, data = read_arff(arff)
import random
data = random.sample(data, nb_elements)

write_arff(header, data, outarff)
