#!/usr/bin/env python2.7

import arff
import sys
#arg1 : start from
# arg2 : take
# arg3 : out arff
# arg4 : out npy
start_from = int(sys.argv[2])
take = int(sys.argv[3])
out_arff = sys.argv[4]
out_npy = sys.argv[5]

i = 0
real_line = 0
import numpy as np
data = []
targets = []
f = open(sys.argv[1])

out_arff = open(out_arff, "w")
while i < take: 
    l = f.readline()
    if len(l)==0:
        break
    if l[0] == '@' or l == "\n":
        if l != "\n" :
            out_arff.write(l)
        continue
    else:
        l = l[0:-1]
        D = l.split(",")
        if len(D)>1:
            #del D[-2]#naomi
            if len(D) == 9722:
                del D[-2]
            if real_line>=start_from:
                out_arff.write(",".join(D)+"\n")
                data.append(map(lambda x:float(x.strip()), D[0:-1]))
                targets.append(D[-1].strip())
                i += 1
            real_line += 1
f.close()

out_arff.close()
np.save(out_npy, (data, targets))
